version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:2024.04.4
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command:  |
            sudo -S apt-get install build-essential cmake -y
            pip3 install virtualenv
            virtualenv -p python3 .venv
            source .venv/bin/activate
            pip install -r requirements/requirements-dev.txt
      - run:
          name: Running tests
          command: |
            source .venv/bin/activate
            pytest
