version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.7.5
     steps:
       - checkout
       - run:
           name: Install python dependencies
           command:  |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements/requirements-dev.txt
       - run:
           name: Running tests
           command: |
               source .venv/bin/activate
               pytest
                
           
